version: '3.1'

services:
  mysql:
    image: mysql:5.6
    container_name: mosly_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: mosly
    volumes:
      - ./my-data:/var/lib/mysql
    ports:
      - 3070:3070
  php:
    build:
      context: ./
      dockerfile: ./docker_images/app.dockerfile
    # Tagea a imagem que é construida no dockerfile.
    image: moslyapi:php-fpm
    container_name: mosly_php
    restart: always
    volumes:
      - ./:/var/www/html:rw
    entrypoint:
      - php-fpm
    user: ${CURRENT_UID}
    depends_on:
      - mysql

  web:
    image: nginx:alpine
    container_name: mosly_nginx
    restart: always
    depends_on:
      - php
    volumes:
      - ./nginx/vhost.conf:/etc/nginx/conf.d/default.conf
      - ./:/var/www/html
    environment:
      NGINX_HOST: 'localhost.mosly'
      NGINX_PORT: '80'
    ports:
      - 85:80

volumes:
  mysql-data:
    driver: "local"
